dailytrans/urls.py
from django.urls import path
from dailytrans.views import index, add_transaction, report_monthwise, transaction_summary

app_name = 'dailytrans'

urlpatterns = [
    path('', index, name='index'),
    path('report_monthwise/', report_monthwise, name='report_monthwise'),
    path('transaction-summary/', transaction_summary, name='transaction_summary'),
    path('add_transaction/', add_transaction, name='add_transaction'),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dailytrans.urls')),
]

# Use static() to add url mapping for serving static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dailytrans/models.py
from django.db import models

# Create your models here.


class MainCategory(models.Model):
    main_id = models.AutoField(primary_key=True)
    main_name = models.CharField(max_length=25)

    def __str__(self):
        return self.main_name

    class Meta:
        verbose_name = "Main Category"
        verbose_name_plural = "Main Categories"

    objects = models.Manager()


class SubCategory(models.Model):
    subcategory_id = models.AutoField(primary_key=True)
    subcategory_name = models.CharField(max_length=25)

    def __str__(self):
        return self.subcategory_name

    class Meta:
        verbose_name = "Sub Category"
        verbose_name_plural = "Sub Categories"

    objects = models.Manager()


class Transactions(models.Model):
    TRANSACTION_TYPE_CHOICES = (
        ('income', 'Income'),
        ('expense', 'Expense'),
    )

    PAYMENT_MODE_CHOICES = (
        ('cash', 'Cash'),
        ('enbd', 'ENBD'),
        ('nol', 'NoL'),
        ('payit', 'PayIT'),
        ('sib', 'SIB'),
    )

    trans_id = models.AutoField(primary_key=True)
    trans_date = models.DateField(verbose_name="Date", db_index=True)
    trans_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE_CHOICES, verbose_name="Type")
    trans_main_category = models.ForeignKey(MainCategory, on_delete=models.CASCADE, verbose_name="Main Category",
                                            related_name="transactions")
    trans_sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, verbose_name="Sub Category",
                                           related_name="transactions")
    trans_mode = models.CharField(max_length=10, choices=PAYMENT_MODE_CHOICES, verbose_name="Payment Mode",
                                  db_index=True)
    trans_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Amount")

    objects = models.Manager()

    class Meta:
        verbose_name = "Transaction"
        verbose_name_plural = "Transactions"

    def __str__(self):
        amount_str = "${:,.2f}".format(self.trans_amount)
        if self.trans_type == 'expense':
            amount_str = "-{}".format(amount_str)

        return (
            f"Transaction ID: {self.trans_id}\n"
            f"Date: {self.trans_date}\n"
            f"Type: {self.trans_type}\n"
            f"Main Category: {self.trans_main_category}\n"
            f"Sub Category: {self.trans_sub_category}\n"
            f"Payment Mode: {self.trans_mode}\n"
            f"Amount: {amount_str}"
        )

dailytrans/forms/add_transaction.py
from django import forms
from django.utils import timezone
from dailytrans.models import Transactions, MainCategory, SubCategory

TRANSACTION_TYPE_CHOICES = [
    ('income', 'Income'),
    ('expense', 'Expense'),
]


PAYMENT_MODE_CHOICES = [
    ('cash', 'Cash'),
    ('enbd', 'ENBD'),
    ('nol', 'NoL'),
    ('payit', 'PayIT'),
    ('sib', 'SIB'),
]


class AddTransactionForm(forms.ModelForm):
    trans_date = forms.DateField(initial=timezone.now().date(), widget=forms.DateInput(attrs={'type': 'date'}))
    trans_type = forms.ChoiceField(choices=Transactions.TRANSACTION_TYPE_CHOICES)
    trans_main_category = forms.ModelChoiceField(queryset=MainCategory.objects.all())
    trans_sub_category = forms.ModelChoiceField(queryset=SubCategory.objects.all())
    trans_mode = forms.ChoiceField(choices=PAYMENT_MODE_CHOICES)
    trans_amount = forms.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        model = Transactions
        fields = '__all__'

    def clean_trans_amount(self):
        trans_type = self.cleaned_data.get('trans_type')
        trans_amount = self.cleaned_data.get('trans_amount')
        if trans_type == 'expense':
            trans_amount = -trans_amount
        return trans_amount

    def clean_trans_mode(self):
        trans_mode = self.cleaned_data.get('trans_mode')
        return trans_mode.lower()

dailytrans/views.py
from django.shortcuts import render

# Create your views here.

dailytrans/views/add_transaction.py
from django.shortcuts import render
from dailytrans.forms import AddTransactionForm
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required

@login_required
def add_transaction(request):
    add_transaction_form_form_set = formset_factory(AddTransactionForm, extra=1)
    if request.method == 'POST':
        formset = add_transaction_form_form_set(request.POST)
        if formset.is_valid():
            for form in formset:
                transaction = form.save(commit=False)
                transaction.user = request.user
                transaction.save()
            # redirect to some page after saving all forms
    else:
        formset = add_transaction_form_form_set()
    context = {'formset': formset}

    return render(request, 'add_transaction.html', context)

dailytrans/views/index.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

dailytrans/views/report_monthwise.py
import calendar
from django.db.models import Sum
from django.shortcuts import render
from dailytrans.models import Transactions


def report_monthwise(request):
    months = Transactions.objects.values('trans_date__month').distinct()
    data = {}
    running_total = 0
    running_total_modes = {}
    monthly_balance = 0
    for obj in months:
        month = calendar.month_name[obj['trans_date__month']]
        qs = (
            Transactions.objects
            .filter(trans_date__month=obj['trans_date__month'])
            .order_by('trans_id', 'trans_date')  # Add ordering to ensure correct running total
        )
        total_modes = {}
        for trans in qs:
            monthly_balance += trans.trans_amount
            running_total += trans.trans_amount
            trans.running_total = running_total
            # Update running total for each trans_mode
            mode_total = running_total_modes.get(trans.trans_mode, 0)
            mode_total += trans.trans_amount
            running_total_modes[trans.trans_mode] = mode_total
            trans.running_total_modes = f"{mode_total}|{trans.trans_mode}"
            # Update total modes for this month
            mode_month_total = total_modes.get(trans.trans_mode, 0)
            mode_month_total += trans.trans_amount
            total_modes[trans.trans_mode] = mode_month_total

        amount = qs.aggregate(total=Sum('trans_amount'))

        # Add this month's data to the overall data dictionary
        data[obj['trans_date__month']] = {
            'month': month,
            'qs': qs,
            'total': amount['total'],
            'total_modes': total_modes,
            'monthly_balance': monthly_balance,
            'running_total': running_total,
            'running_total_modes': running_total_modes.copy()  # Make a copy to avoid modifying the running total dict
        }

    context = {'data': data}

    return render(request, 'report_monthwise.html', context)

dailytrans/views/transaction_summary.py
from django.db.models import Case, Sum, Value, When
from django.db.models.functions import TruncMonth
from django.db import models
from django.shortcuts import render
from dailytrans.models import Transactions


def transaction_summary(request):
    cols = [{'name': 'Cash', 'label': 'Cash'}, {'name': 'ENBD', 'label': 'ENBD'}, {'name': 'NoL', 'label': 'NoL'},
            {'name': 'PayIT', 'label': 'PayIT'}, {'name': 'SIB', 'label': 'SIB'}]

    totals = Transactions.objects.annotate(
        month=TruncMonth('trans_date')
    ).values(
        'month', 'trans_mode'
    ).annotate(
        tot=Sum('trans_amount'),
        trans_income=Sum(Case(
            When(trans_amount__gt=0, then='trans_amount'),
            default=Value(0),
            output_field=models.DecimalField()
        )),
        trans_expense=Sum(Case(
            When(trans_amount__lt=0, then='trans_amount'),
            default=Value(0),
            output_field=models.DecimalField()
        )),
        balance=Sum('trans_amount'),
    ).order_by()

    total_modes = Transactions.objects.values('trans_mode').annotate(balance=Sum('trans_amount'))

    # Create a dictionary to hold the data
    data = {}

    # Loop through the query results and populate the dictionary
    for row in totals:
        month = row['month'].strftime('%B %Y')
        trans_mode = row['trans_mode']
        if month not in data:
            data[month] = {}
        if trans_mode not in data[month]:
            data[month][trans_mode] = {}
        data[month][trans_mode]['trans_income'] = row['trans_income']
        data[month][trans_mode]['trans_expense'] = row['trans_expense']
        data[month][trans_mode]['balance'] = row['balance']

    # Add the total_modes to the data dictionary
    for rows in total_modes:
        trans_modes = rows['trans_mode']
        if 'Total' not in data:
            data['Total'] = {}
        if trans_modes not in data['Total']:
            data['Total'][trans_modes] = {}
        data['Total'][trans_modes]['balance'] = rows['balance']

    # Pass the dictionary to the template for rendering
    return render(request, 'transaction_summary.html', {'data': data, 'cols': cols, 'total_modes': total_modes})

dailytrans/templates/add_transaction.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-4">Add Transaction</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset.forms %}
        <table>
            {{ form.as_table }}
        </table>
        {% endfor %}
        <input type="submit" value="Save">
    </form>

    {% if form.errors %}
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {% for field, errors in form.errors.items %}
        <p>{{ field }}: {{ errors|join:", " }}</p>
        {% endfor %}
    </div>
    {% endif %}

</div>
{% endblock %}

{% block extra_js %}
<script>
  $(function() {
    $('#id_trans_date').datepicker({
      dateFormat: 'yy-mm-dd'
    });
  });

</script>
{% endblock %}

dailytrans/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" rel="stylesheet">

    <!-- Bootstrap JS bundle (including Popper.js) -->
    <script crossorigin="anonymous"
            integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"></script>
            <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        border: 2px solid black;
        padding: 8px;
        text-align: left;
      }

      ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
      }

      li {
        float: left;
        border-right:1px solid #bbb;
      }

      li:last-child {
        border-right: none;
      }

      li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }

      li a:hover:not(.active) {
        background-color: #111;
      }

      .active {
        background-color: #04AA6D;
      }

      .navbar-menu {
        display: flex;
        justify-content: space-between;
      }

      .navbar-menu li:last-child {
        margin-left: auto;
      }

      /* Set the navbar to be fixed to the top */
      .navbar {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 999;
        background-color: #f8f8f8;
      }

      /* Add some padding to the content below the navbar */
      .content {
        padding-top: 60px; /* Adjust this value according to your navbar height */
      }

      /* Hide the navbar when printing */
      @media print {
        .navbar {
          display: none;
        }
      }

        .red-text {
          color: red;
        }

        .green-text {
          color: green;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #4CAF50;
            color: white;
        }

        .month-table {
            border: 1px solid #ddd;
            margin-bottom: 20px;
            width: 100%;
        }

        .month-title {
            background-color:  #0000ff;
            color: white;
            font-size: 20px;
            font-weight: bold;
            padding: 10px;
            text-align: center;
        }

        .account-name {
            font-weight: bold;
        }

        .total-table {
            margin-top: 30px;
            width: 50%;
        }

        .total-title {
            background-color:  #0000ff;
            color: white;
            font-size: 20px;
            font-weight: bold;
            padding: 10px;
            text-align: center;
        }
        .cash-mode {
            color: blue;
            font-weight: bold;
        }

        .enbd-mode {
            color: brown;
            font-weight: bold;
            font-style: italic;
        }

        .nol-mode {
            color: orange;
            text-decoration: underline;
        }

        .payit-mode {
            color: red;
            font-weight: bold;
            text-decoration: line-through;
        }

        .sib-mode {
            color: purple;
            font-style: italic;
            text-decoration: underline;
        }
    </style>
  </head>
  <body>
    <!-- Include the navbar HTML code here -->

    {% include 'navbar.html' %}

    <!-- Include the main content of the page here -->
    <div class="content">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

dailytrans/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Welcome to the home page!</h1>
{% endblock %}

dailytrans/templates/navbar.html
<nav class="navbar">
  <ul class="navbar-menu">
    <li><a href="{% url 'dailytrans:index' %}" class="{% if request.path == '/' %}active{% endif %}">Home</a></li>
    <li><a href="{% url 'dailytrans:report_monthwise' %}">Monthly Report</a></li>
    <li><a href="{% url 'dailytrans:add_transaction' %}">Add</a></li>
    <li><a href="{% url 'dailytrans:transaction_summary' %}">Transaction Summary</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
  </ul>
</nav>

dailytrans/templates/report_monthwise.html
{% extends 'base.html' %}
{% load utils %}
{% block content %}
<body>
  {% for key, value in data.items %}
    {% if not forloop.first %}<div class="page-break"></div>{% endif %}
    <h1>Monthly Report - {{ value.month }}</h1>
    <h3>Total: <a>{{ value.total | cf | safe }}</a>
    <a style="float:right"> Balance:  {{ value.monthly_balance | cf | safe }}</a></h3>
    <table border="2" style="width: 100%; border-collapse: collapse;">
      <thead>
        <tr>
          <th>ID</th>
          <th>Date</th>
          <th>Pay Mode</th>
          <th>Category</th>
          <th>Sub Category</th>
          <th>Amount</th>
          <th>Mode Wise</th>
          <th>Running Total</th>
        </tr>
      </thead>
      <tbody>
        {% for trans in value.qs %}
          <tr>
            <td>{{ trans.trans_id }} </td>
            <td>{{ trans.trans_date }}</td>
            <td>{{ trans.trans_mode }}</td>
            <td>{{ trans.trans_main_category }}</td>
            <td>{{ trans.trans_sub_category }}</td>
            <td>{{ trans.trans_amount | cf | safe }}</td>
            <td>{{ trans.running_total_modes | cf_mode | safe }}</td>
            <td>{{ trans.running_total | cf | safe }}</td>
          </tr>
          {% if forloop.last %}
          <table border="2">
              <tr>
                <td>Cash</td>
                <td>Enbd</td>
                <td>NoL</td>
                <td>Pay IT</td>
                <td>SIB</td>
                <td>Total</td>
              </tr>
              <tr>
                <td><b>{{ value.running_total_modes.Cash | cf | safe }}</b></td>
                <td><b>{{ value.running_total_modes.ENBD | cf | safe }}</b></td>
                <td><b>{{ value.running_total_modes.NoL | cf | safe }}</b></td>
                <td><b>{{ value.running_total_modes.PayIT | cf | safe  }}</b></td>
                <td><b>{{ value.running_total_modes.SIB | cf | safe  }}</b></td>
                <td><b>{{ value.running_total | cf | safe  }}</b></td>
              </tr>
            </table>
          {% endif %}
        {% endfor %}
      </tbody>
      </table>
  <hr style="border: 2px solid black; display: block;"> <!-- Add a horizontal line here -->
  {% endfor %}
</body>
{% endblock %}

dailytrans/templates/test.html
{% extends 'base.html' %}

{% block content %}
<table border="2">
  <tr>
    <td>Trans Mode</td>
    {% for month_data in data.values %}
      <td>{{ month_data.month }}</td>
    {% endfor %}
  </tr>
  <tr>
    <td>Cash</td>
    {% for month_data in data.values %}
      <td><b>{{ month_data.running_total_modes.Cash|default:"0" | floatformat:"2g" }}</b></td>
    {% endfor %}
  </tr>
  <tr>
    <td>Enbd</td>
    {% for month_data in data.values %}
      <td><b>{{ month_data.running_total_modes.ENBD|default:"0" | floatformat:"2g" }}</b></td>
    {% endfor %}
  </tr>
  <tr>
    <td>NoL</td>
    {% for month_data in data.values %}
      <td><b>{{ month_data.running_total_modes.NoL|default:"0" | floatformat:"2g" }}</b></td>
    {% endfor %}
  </tr>
  <tr>
    <td>Pay IT</td>
    {% for month_data in data.values %}
      <td><b>{{ month_data.running_total_modes.PayIT|default:"0" | floatformat:"2g" }}</b></td>
    {% endfor %}
  </tr>
  <tr>
    <td>SIB</td>
    {% for month_data in data.values %}
      <td><b>{{ month_data.running_total_modes.SIB|default:"0" | floatformat:"2g" }}</b></td>
    {% endfor %}
  </tr>
</table>

{% endblock %}

dailytrans/templates/test2.html
{% extends 'base.html' %}
{% load utils %}
{% block content %}
  <table border="2">
    <tr>
      <td></td>
      {% for month_data in data.values %}
        <td colspan="3"><b>{{ month_data.month }}</b></td>
      {% endfor %}
    </tr>
    <tr>
      <td></td>
      {% for month_data in data.values %}
        <td><b>Income</b></td>
        <td><b>Expense</b></td>
        <td><b>Balance</b></td>
      {% endfor %}
    </tr>
    {% for mode in modes %}
      <tr>
        <td>{{ mode }}</td>
        {% for month_data in data.values %}
          <td>
            {% if mode in month_data.total_modes %}
              {{ month_data.total_modes|get_item:mode|floatformat:"2g" }}
            {% else %}
              0.00
            {% endif %}
          </td>
          <td>
            {% if mode in month_data.total_expense_modes %}
              {{ month_data.total_expense_modes|get_item:mode|floatformat:"2g" }}
            {% else %}
              0.00
            {% endif %}
          </td>
          <td>
            {% if mode in month_data.total_modes and mode in month_data.total_expense_modes %}
              {{ month_data.total_modes|get_item:mode|default:"0" |floatformat:"2g" }} - {{ month_data.total_expense_modes|get_item:mode|default:"0" | floatformat:"2g" }}
            {% elif mode in month_data.total_modes %}
              {{ month_data.total_modes|get_item:mode|floatformat:"2g" }}
            {% elif mode in month_data.total_expense_modes %}
              -{{ month_data.total_expense_modes|get_item:mode|floatformat:"2g" }}
            {% else %}
              0.00
            {% endif %}
          </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </table>
{% endblock %}

dailytrans/templates/test3.html
{% extends 'base.html' %}
{% block content %}
<table>
  <thead>
    <tr>
      <th rowspan="2">Trans Mode</th>
      <th colspan="3">January 2023</th>
      <th colspan="3">February 2023</th>
      <th colspan="3">March 2023</th>
      <th colspan="3">April 2023</th>
    </tr>
    <tr>
      <th>Total Income</th>
      <th>Total Expense</th>
      <th>Balance</th>
      <th>Total Income</th>
      <th>Total Expense</th>
      <th>Balance</th>
      <th>Total Income</th>
      <th>Total Expense</th>
      <th>Balance</th>
      <th>Total Income</th>
      <th>Total Expense</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
    {% for trans_mode, months in summary.items %}
      <tr>
        <td>{% if trans_mode == 'Cash' %} colspan="3"{% endif %}>{{ trans_mode }}
        {% for month, data in months.items %}
          <td>{{ data.total_income }}</td>
          <td>{{ data.total_expense }}</td>
          <td>{{ data.balance }}</td>
        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>

{{ summary }}
{% endblock %}

dailytrans/templates/transaction_summary.html
{% extends 'base.html' %}
{% load utils %}
{% block content %}
<body>

{% for month, accounts in data.items %}
    <div class="month-table">
        <div class="month-title">Transaction summary for {{ month }}</div>
        <table>
            <tr>
                <th>Account</th>
                <th>Income</th>
                <th>Expense</th>
                <th>Balance</th>
            </tr>
            {% for account, values in accounts.items %}
                <tr>
                    <td class="account-name">{{ account }}</td>
                    <td>{{ values.trans_income | cf | safe}}</td>
                    <td>{{ values.trans_expense | cf | safe }}</td>
                    <td>{{ values.balance | cf | safe }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endfor %}
{% endblock %}